../src/DatapathCore/zero_detector.vhd
../src/DatapathCore/T2_shifter_generic.vhd
../src/DatapathCore/T2_Logic_Unit.vhd
../src/DatapathCore/Srt_divider/Srt_divider_core/zeroesCounter.vhd
../src/DatapathCore/Srt_divider/Srt_divider_core/twosCompBlock.vhd
../src/DatapathCore/Srt_divider/Srt_divider_core/SRTWrapper.vhd
../src/DatapathCore/Srt_divider/Srt_divider_core/SRTDivider.vhd
../src/DatapathCore/Srt_divider/Srt_divider_core/SRTController.vhd
../src/DatapathCore/Srt_divider/Srt_divider_core/digitLUT.vhd
../src/DatapathCore/Srt_divider/radix4_SRTDivider_toplevel.vhd
../src/DatapathCore/sign_extender.vhd
../src/DatapathCore/registerfile.vhd
../src/DatapathCore/pipeRegisterOneBit.vhd
../src/DatapathCore/pipeRegister.vhd
../src/DatapathCore/P4_adder/P4_adder_core/arithm_function.vhd
../src/DatapathCore/P4_adder/P4_adder_core/sum_generator.vhd
../src/DatapathCore/P4_adder/P4_adder_core/ripple_carry_adder.vhd
../src/DatapathCore/P4_adder/P4_adder_core/PGNetwork.vhd
../src/DatapathCore/P4_adder/P4_adder_core/PGBlock.vhd
../src/DatapathCore/P4_adder/P4_adder_core/GBlock.vhd
../src/DatapathCore/P4_adder/P4_adder_core/carry_select_adder.vhd
../src/DatapathCore/P4_adder/P4_adder_core/carry_generator.vhd
../src/DatapathCore/P4_adder/p4_adder.vhd
../src/DatapathCore/Memories/IRAM.vhd
../src/DatapathCore/Memories/DRAM.vhd
../src/DatapathCore/comparator.vhd
../src/DatapathCore/Booth_multiplier/boothMul.vhd
../src/DatapathCore/Booth_multiplier/Booth_multiplier_core/twosCompBlock.vhd
../src/DatapathCore/Booth_multiplier/Booth_multiplier_core/boothMulDatapath.vhd
../src/DatapathCore/Booth_multiplier/Booth_multiplier_core/boothMulController.vhd
../src/./datapath.vhd
../src/./controller.vhd
../src/./dlx.vhd
./testbenches/tb_dlx.vhd
